spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DATABASE}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVICE_URL}/.well-known/jwks.json