spring.application.name=payment-service

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DATABASE}

mongock.migration-scan-package=com.innowise.paymentservice.changelog

random-api.url=${RANDOM_API_URL}